import assert from 'node:assert/strict';
import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {build} from 'esbuild';
import {PDFDocument} from 'pdf-lib';
await mkdir('tmp/pdfs',{recursive:true});
await build({entryPoints:['lib/project-pdf.ts','lib/shot-list.ts','lib/production.ts'],bundle:true,platform:'node',format:'esm',packages:'external',outdir:'.work/pdf-test'});
const {createProjectPdf}=await import('../.work/pdf-test/project-pdf.js');
const {exampleProject,blankProject,blankShot}=await import('../.work/pdf-test/shot-list.js');
const {productionOf,ALL_MODULES}=await import('../.work/pdf-test/production.js');
const project=exampleProject();project.id='11111111-1111-4111-8111-111111111111';project.title='Nightfall - Studio campaign';project.date='2026-10-10';project.client='Smooth Studios';project.revision=1;
project.production={...productionOf(project),modules:[...ALL_MODULES],budgetCents:95000,tasks:[{id:crypto.randomUUID(),title:'Prepare camera and lighting package',assignee:'crew-1',department:'Pre-production',due:'2026-10-09',status:'In progress',notes:'Charge batteries and confirm the talent wardrobe.'}],documents:[{id:crypto.randomUUID(),title:'Creative treatment',kind:'Treatment',content:'Every client has a story.\n\nA quiet opening gives way to a striking portrait. José steps into the light.\n\n'+Array(28).fill('INT. STUDIO - NIGHT\nThe camera holds on the reflection. She steps away, but the reflection stays.').join('\n\n'),url:'',updatedAt:1}],schedule:[{id:crypto.randomUUID(),date:'2026-10-10',start:'18:00',end:'19:00',title:'Portrait sequence',type:'Shoot',location:'Studio A',notes:'Begin with scene 2, then pick up inserts.',shotIds:project.shots.slice(0,2).map(s=>s.id)}],expenses:[{id:crypto.randomUUID(),title:'Lighting package',category:'Equipment',plannedCents:25000,actualCents:24500,paid:true,vendor:'Rental house',date:'2026-10-10',notes:'Two lights, stands, and diffusion.'}],callSheet:{date:'2026-10-10',call:'17:00',wrap:'21:00',location:'Smooth Studios',address:'Studio A - test location',parking:'Arrive at the front entrance.',contactName:'Smooth',contactPhone:'Test contact',safety:'Keep exits and cable paths clear.',notes:'Bring water and comfortable shoes.'}};
const imageBytes=Uint8Array.from(Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=','base64'));
project.shots[0].references=[{id:'22222222-2222-4222-8222-222222222222',name:'Framing reference.png',caption:'REFERENCE CHECK - preserve image aspect ratio.'}];
project.fields.push({key:'continuity',label:'Continuity notes for wardrobe, blocking, practical lighting, and camera position',type:'textarea',group:'Notes',visible:true,custom:true});
project.shots[0].values.continuity='Maintain the same hand position and practical lamp brightness between angles. '+('Long continuity note. '.repeat(30));
const crew=[{id:'crew-1',projectId:project.id,name:'Akiva',email:'test@example.invalid',role:'Producer',phone:'Test phone',callTime:'17:00'}];
const files=[{id:'file-1',projectId:project.id,name:'Client reference.pdf',category:'Reference',mime:'application/pdf',size:14000,createdAt:1}];
const simple=blankProject('Simple portrait session');simple.id='33333333-3333-4333-8333-333333333333';simple.revision=1;simple.shots=[blankShot()];simple.shots[0].description='A simple portrait against the seamless backdrop.';
assert.deepEqual(productionOf(simple).modules,[]);assert.deepEqual(productionOf({production:undefined}).modules,ALL_MODULES);
const options={sections:['overview','shots','crew','files','schedule','budget'],images:true,regularFont:new Uint8Array(await readFile('public/fonts/ProductionSans.ttf')),boldFont:new Uint8Array(await readFile('public/fonts/ProductionSans-Bold.ttf')),loadImage:async()=>({bytes:imageBytes,mime:'image/png'})};
const result=await createProjectPdf([{project,crew,files},{project:simple,crew:[],files:[]}],options);
assert.deepEqual(result.warnings,[]);assert.ok(result.pageCount>=9);assert.equal((await PDFDocument.load(result.bytes)).getPageCount(),result.pageCount);
await writeFile('tmp/pdfs/production-export-check.pdf',result.bytes);
const solo=await createProjectPdf([{project:simple,crew:[],files:[]}],{...options,sections:['shots']});assert.equal(solo.pageCount,1);
const noImage=await createProjectPdf([{project,crew,files}],{...options,sections:['shots'],images:false,loadImage:async()=>{throw new Error('Must not load images');}});assert.equal(noImage.warnings.length,0);
await assert.rejects(()=>createProjectPdf([{project:simple,crew:[],files:[]}],{...options,sections:['budget']}),/None of the selected sections/);
await writeFile('tmp/pdfs/ui-fixture.json',JSON.stringify({project,simple,crew,files},null,2));
console.log('PDF checks passed: combined projects, individual sections, opt-in modules, Unicode names, long scripts, image inclusion, image exclusion, and pagination ('+result.pageCount+' pages).');
