import {useEffect,useState} from 'react';
import {Check,ChevronRight,Link2,Loader2,Plus,Settings,Users,X} from 'lucide-react';
import {Button} from './ui/button';
import {Checkbox} from './ui/checkbox';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription,DialogFooter} from './ui/dialog';
import {AlertDialog,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from './ui/alert-dialog';
import {TeamAccounts} from './accounts';
import {request,errorText} from './production-ui';
import {MODULES,RENTAL_DASHBOARD_URL,type ProductionModule,type CrewMember} from '@/lib/production';
import {toast} from 'sonner';

type TeamAccount={id:string;name:string;username:string;email:string;enabled:boolean};
export function ModulePicker({value,onChange,editing=false}:{value:ProductionModule[];onChange:(v:ProductionModule[])=>void;editing?:boolean}){
 return <fieldset className="project-options"><legend>Project sections</legend><p>The shot list is included. Add only what this production needs.</p><div className="module-picker">{MODULES.map(m=><label key={m.key} className={'option-card '+(value.includes(m.key)?'selected':'')}><Checkbox checked={value.includes(m.key)} onCheckedChange={checked=>onChange(checked?[...value,m.key]:value.filter(k=>k!==m.key))}/><span><strong>{m.label}</strong><small>{m.description}</small></span></label>)}</div><small>{editing?'Turning off a section keeps its saved contents and team access. You can turn it back on anytime.':'You can add or remove sections later in Project details.'}</small></fieldset>;
}
export function TeamPicker({value,onChange,excludeEmails=[]}:{value:string[];onChange:(v:string[])=>void;excludeEmails?:string[]}){
 const [accounts,setAccounts]=useState<TeamAccount[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState('');
 async function load(){setLoading(true);setError('');try{const data=await request<{accounts:TeamAccount[]}>('/api/team');setAccounts(data.accounts.filter(a=>a.enabled&&a.id!=='owner'));}catch(e){setError(errorText(e));}finally{setLoading(false);}}
 useEffect(()=>{load();},[]);
 const available=accounts.filter(a=>!excludeEmails.includes(a.email||a.username+'@production.invalid'));
 return <fieldset className="project-options"><legend>Tag team members</legend><p>Tag the people working on this production. Everyone on the team can view it; assigned members can edit.</p>{loading?<p role="status"><Loader2 className="spin" size={16}/>Loading team…</p>:error?<div className="module-error" role="alert">{error}<Button type="button" variant="outline" size="sm" onClick={load}>Retry</Button></div>:available.length?<div className="team-picker">{available.map(a=><label className={'team-option '+(value.includes(a.id)?'selected':'')} key={a.id}><Checkbox checked={value.includes(a.id)} onCheckedChange={checked=>onChange(checked?[...value,a.id]:value.filter(id=>id!==a.id))}/><span><strong>{a.name}</strong><small>@{a.username}</small></span></label>)}</div>:<p className="module-muted">{accounts.length?'All active team members are already tagged.':'Create team accounts in Settings to tag people here.'}</p>}</fieldset>;
}
export function ProjectTeam({projectId,crew,admin,onChange,loading=false}:{projectId?:string;crew:CrewMember[];admin:boolean;onChange:()=>Promise<void>;loading?:boolean}){
 const [open,setOpen]=useState(false),[selected,setSelected]=useState<string[]>([]),[busy,setBusy]=useState(false),[remove,setRemove]=useState<CrewMember|null>(null);
 async function tag(){setBusy(true);try{for(const accountId of selected){await request('/api/projects/'+projectId+'/crew','POST',{accountId});setSelected(ids=>ids.filter(id=>id!==accountId));}setOpen(false);toast.success('Team members tagged');}catch(e){toast.error(errorText(e));}finally{await onChange();setBusy(false);}}
 return <section className="production-section project-team"><div className="section-heading"><div><h2><Users size={18}/>Project team</h2><p>{admin?'Link team members to this production, with or without Crew & Tasks.':'People assigned to this production.'}</p></div>{admin&&<Button variant="outline" disabled={!projectId||loading} onClick={()=>{setSelected([]);setOpen(true);}}><Plus size={16}/>Tag team member</Button>}</div>{loading?<p className="module-muted">Loading team…</p>:<div className="team-tags">{crew.map(m=><span className="team-tag" key={m.id}><span className="tag-avatar">{m.name.charAt(0)}</span><span><strong>{m.name}</strong><small>{m.role}</small></span>{admin&&<Button size="icon" variant="ghost" aria-label={'Remove '+m.name+' from project'} onClick={()=>setRemove(m)}><X size={14}/></Button>}</span>)}{!crew.length&&<p className="module-muted">{projectId?'No team members tagged yet.':'Save this project to tag team members.'}</p>}</div>}
 <Dialog open={open} onOpenChange={v=>!busy&&setOpen(v)}><DialogContent className="production-modal"><DialogHeader><DialogTitle>Tag team members</DialogTitle><DialogDescription>Select the people who will work on this production.</DialogDescription></DialogHeader><div className="production-modal-body"><TeamPicker value={selected} onChange={setSelected} excludeEmails={crew.map(m=>m.email)}/></div><DialogFooter><Button variant="outline" disabled={busy} onClick={()=>setOpen(false)}>Cancel</Button><Button disabled={busy||!selected.length} onClick={tag}>{busy?<Loader2 className="spin"/>:<Check/>}Tag members</Button></DialogFooter></DialogContent></Dialog>
 <AlertDialog open={!!remove} onOpenChange={v=>!v&&!busy&&setRemove(null)}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Remove {remove?.name} from this project?</AlertDialogTitle><AlertDialogDescription>This removes their assignment and editing permission. They can still view this production.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel disabled={busy}>Cancel</AlertDialogCancel><AlertDialogAction disabled={busy} onClick={async e=>{e.preventDefault();setBusy(true);try{await request('/api/projects/'+projectId+'/crew','DELETE',{memberId:remove?.id});await onChange();setRemove(null);}catch(e){toast.error(errorText(e));}finally{setBusy(false);}}}>Remove member</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 </section>;
}
export function DashboardSettings({admin}:{admin:boolean}){
 return <div className="production-home dashboard-settings"><div className="production-home-heading"><div><div className="eyebrow">PRODUCTION DASHBOARD</div><h1>Settings</h1><p>Your studio links and team account management.</p></div><Settings className="settings-icon"/></div><section className="production-section"><h2 className="settings-section-title">Connected dashboards</h2><a className="settings-dashboard-link" href={RENTAL_DASHBOARD_URL} target="_blank" rel="noopener noreferrer"><Link2/><span><strong>Studio Dashboard</strong><small>Open studio rentals, schedules, and payroll.</small></span><ChevronRight/></a></section>{admin&&<div className="settings-team"><TeamAccounts/></div>}</div>;
}
